version: '3.1'

services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend-docker
    restart: always
    environment:
      - FLASK_APP=main.py
    links:
      - db
  # Create database container
  db:
    image: postgres:11.6-alpine
    expose:
      - "5432"
    ports:
    - "5001:5432"
    container_name: database-docker
    restart: always
