version: '3.1'

services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    container_name: frontend-docker
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    volumes:
      - ./frontend:/app
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    container_name: backend-docker
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_APP=src/main.py
    links:
      - db
  # Create database container
  db:
    image: postgres:11.6-alpine
    expose:
      - "5432"
    ports:
    - "5001:5432"
    container_name: database-docker
    restart: always
